spring:
  freemarker:
    suffix: .ftl  #加载后缀,设定 ftl 文件路径
    cache: false  #Freemarker页面不加载缓存，实现修改即时生效
    #mvc:
    #static-path-pattern: /static/**

  web:
    resources:
      static-locations: classpath:/static/
  devtools:
    restart:
      enabled: true #开启热部署
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/person?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT
    username: root
    password: mysql159612
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      #enable_lazy_load_no_trans: true #使用延时加载时控制Session的生命周期  修改
      #dialect: org.hibernate.dialect.MySQL5Dialect  #修改
      ddl-auto: update #如果这里是create，则在每次更新后台之后，数据库中的内容都会被清空
    show-sql: true
    open-in-view: false  #使用延时加载，控制 Session 的生命周期  #修改
server: #配置应用名
  servlet:
    context-path: /personnel
  jackson:
    default-property-inclusion: non_null